/// Generated by AssetsRefGenerator on 2022/05/01
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String dapps = "assets/images/dapps.svg";
  static const String discover = "assets/images/discover.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String geometric = "assets/images/geometric.svg";
  static const String home = "assets/images/home.svg";
  static const String icon = "assets/images/icon.png";
  static const String loginType_header = "assets/images/loginType_header.png";
  static const String logo = "assets/images/logo.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
  static const String settings = "assets/images/settings.svg";
  static const String welcome1 = "assets/images/welcome1.svg";
  static const String welcome2 = "assets/images/welcome2.svg";
  static const String welcome3 = "assets/images/welcome3.svg";
  static const String welcomeHeader = "assets/images/welcomeHeader.svg";
}
