/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
}
