/// Generated by AssetsRefGenerator on 2022/03/01
class Res {
  static const String ar = "assets/lang/ar.json";
  static const String en = "assets/lang/en.json";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String marker = "assets/images/marker.png";
}
